rtc_base/physical_socket_server.cc

On Debian 11 socket creation fails
`(turn_port.cc:389): Port[a800fbb0:data:1:0:relay:Net[eth0:10.35.11.x/24:Ethernet:id=1]]: Trying to connect to TURN server via udp @ global.turn.twilio.com:3478
(turn_port.cc:389): Port[a800fbb0:data:1:0:relay:Net[eth0:10.35.11.x/24:Ethernet:id=1]]: Trying to connect to TURN server via udp @ global.turn.twilio.com:3478
(physical_socket_server.cc:243): Binding socket to network interface index 3 failed
(physical_socket_server.cc:243): Binding socket to network interface index 3 failed
(basic_packet_socket_factory.cc:48): UDP bind failed with error 0
(basic_packet_socket_factory.cc:48): UDP bind failed with error 0
(turn_port.cc:393): Failed to create TURN client socket
(turn_port.cc:393): Failed to create TURN client socket`

Soecket option OPT_IFACE_BIND available on iOS and MacOS only

---

DEPS
rtc_base/rate_limiter.cc

https://ubiquiti.atlassian.net/browse/UPC-3499
Related PR in libjingle-build https://github.com/ubiquiti/libjingle-build/pull/11

[UPC-3499] Google WebRTC XCframework is missing tvOS simulator build

---

BUILD.gn
api/video/video_bitrate_allocation.cc
api/video/video_bitrate_allocation.h
modules/pacing/pacing_controller.cc
modules/pacing/pacing_controller.h
modules/pacing/task_queue_paced_sender.cc
modules/pacing/task_queue_paced_sender.h
modules/video_coding/utility/frame_dropper.cc
modules/video_coding/utility/frame_dropper.h
video/video_stream_encoder.cc
video/video_stream_encoder.h
webrtc.gni

As discuss in slack:
1. Add new definition building flag for bitrate adjustment and disable it by default as we've already reduced it by 12.5% in addon.
2. Remove changes in pacing module.

Adjust our changes in Google WebRTC

---

modules/congestion_controller/goog_cc/delay_based_bwe.cc
modules/remote_bitrate_estimator/aimd_rate_control.cc

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-3714)
1. Modify the state machine in AIMD rate control module, and speed up recovery.
2. Recover bitrate more quickly when the bandwidth usage state changed in some cases.

[UPC 3714] Bitrate is low in case of good network condition with multiple camera streams.

---

modules/congestion_controller/goog_cc/delay_based_bwe.cc
modules/congestion_controller/goog_cc/probe_controller.cc
modules/remote_bitrate_estimator/aimd_rate_control.cc

1. Restore changes about increased limit in AIMD control.
2. Currently, we use periodic probing every 5 secs, so if the result of probe is less than current estimated, we use current value instead of the probing result to make sure bitrate won't have a big drop due to our probing.

No further probing for periodic probes and let bitrate won't drop that fast for better UX.

---

video/video_send_stream_impl.cc

1. We still need encoder activity detector for effective usage of bitrate, since it will remove the bitrate allocator in the right situation.
2. Even if it is removed, the `SetRates` will be triggered due to we still send encoded image to lib and CC still works due to there is audio data sending or the forced-probing be activated.

improve: we still need encoder activity detector for effective usage of bitrate

---

modules/congestion_controller/goog_cc/probe_controller.cc
modules/congestion_controller/goog_cc/probe_controller.h
modules/pacing/bitrate_prober.h
modules/pacing/pacing_controller.cc

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-4055)
Root cause:
In case of video paused(bitrate below 100kbps) and audio muted, two situations:
1. We aren't in alr state, so probing won't be triggered, bitrate will be recovered slowly so that cause video keep freezing.
2. We are in alr state, but there is no video or audio data sent, so even if a probe request made, no probing packet sent.
Solution:
1. Add a periodic probing, similar to alr probing but a little bit different is whether we want to do further probing. If now is alr probing, then we do further probing as Google did by default, otherwise, just probing once. --> fix situation 1.
2. Forced activate probing in case of video paused and audio muted, it will send a probing packet with about 1 kilobyte which used for bitrate …

fix: [UPC-4055] Google WebRTC media stream often won't resume when returning back to live stream.

---

sdk/objc/components/audio/RTCAudioSession.mm
sdk/objc/components/audio/RTCAudioSessionConfiguration.m

fix: the default value of iOS microphone muting flag is incorrect.

fix: default value should be true for microphone muting.

---

api/rtp_parameters.h
call/bitrate_allocator.cc
call/bitrate_allocator.h
call/video_send_stream.h
media/engine/webrtc_video_engine.cc
modules/congestion_controller/goog_cc/delay_based_bwe.cc
modules/pacing/bitrate_prober.h
modules/pacing/pacing_controller.cc
video/video_send_stream.cc
video/video_send_stream.h
video/video_send_stream_impl.cc
video/video_send_stream_impl.h

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-4333)
1. Add interface for setting video suspended to each stream.
2. Remove probes without sending video and audio data.

feat: [UPC-4333] Enable/disable video suspending for each stream respectively.

---

DEPS

DEPS url tag version lost 'v' , cause build Error.
Fixed DSPS ubnt_libjingle_component_src_build tag version type error
Build Error. "fatal: couldn't find remote ref 0.0.24"
Fixed Right URL:
https://github.com/ubiquiti/ubnt_libjingle_component_src_build.git@v0.0.24
git can checkout tag and build Success
None
None

fixed(DSPS url error)

---

call/call.h
modules/congestion_controller/goog_cc/probe_controller.cc
sdk/BUILD.gn
sdk/objc/components/renderer/metal/RTCMTLRenderer.h
sdk/objc/components/renderer/metal/RTCMTLRenderer.mm

1. fixed apple tvOS platform check issue.
2. fixed cxx17 to cxx20 issue.
3. fixed UI_BITRATE_RECOVERY lost.
- appletv build fail.
- DebianServer Backend build  pure virtual function and function arguments.
- appleTV RTCMTLRenderer.h Method Platform define issue.
Success Ubiquiti All Support Platform : 
- macOS arm64/x86_64
- iOS arm64 / 
- iOS Simulate arm64 / x86_64
- tvOS arm64
- tvOS Simulate arm64 / x86_64
- macOSCatalys arm64 / x86_64 (iOS SDK Framework can run on macOS platform, but macOS Project can use.)
- Android armeabi-v7a / arm64-v8a / x86 / x86_64
- Debian arm64 / x86_64
- Ubuntu
None
None
[UPC-4887]: https://ubiquiti.atlassian.net/browse/UPC-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UPC-4887] Upgrade Google WebRTC to M113

---

Jenkinsfile.pdx
docker/Dockerfile.debian.11.amd64
docker/Dockerfile.debian.11.arm64
docker/Dockerfile.ubuntu.20.04.amd64
docker/Dockerfile.ubuntu.22.04.amd64

- Jenkins can not build macOS and iOS framework.
- Jenkins can not build Debian arm64/x86_64 , Ubuntu x86_64, Android .
- Jenkins can build macOS and iOS framework.
- Upload all platform module and debug Symbol to  artifact server (jfrog).
- Jenkins can build Debian arm64/x86_64 , Ubuntu x86_64, Android by Docker.
- All Platform use TAG_NAME to build.
- Support Parallel Jenkins  Node build module.
None
None

Update Jenksinfile.pdx support build macOS and iOS

---

docker/Dockerfile.ubuntu.22.04.amd64

Fixed Ubuntu Server Update Package version but Docker build cannot fetch right version name.
--allow-releaseinfo-change argument have some security.
Just workaround only modify Ubuntu 22.04 Dockerfile.
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-15/libllvm15_15.0.7-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
New Version :  libllvm15_15.0.7-0ubuntu0.22.04.2_amd64.deb 
http://archive.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-15/libllvm15_15.0.7-0ubuntu0.22.04.2_amd64.deb 
Ubuntu 22.04 Docker file can not build success.
None
None

fix: Ubuntu 22.04 llvm-toolchain-17 deb package installation in docker

---

rtc_base/network.cc
rtc_base/network_monitor.h
sdk/android/src/jni/android_network_monitor.cc
sdk/android/src/jni/android_network_monitor.h
sdk/objc/native/src/objc_network_monitor.h
sdk/objc/native/src/objc_network_monitor.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-5751)
After tracing code back to Google WebRTC [M103](https://webrtc.googlesource.com/src.git/+/0a3d3093dfe54af40bbcb9354fe5661386cd6e48/sdk/android/src/jni/android_network_monitor.cc#429), the codes removed in this PR were made and deprecated by Google, so remove them.

fix: [UPC-5751] Google WebRTC lib crash on Protect android app

---

sdk/BUILD.gn

fix: [UPC-5820] tvOS app cant be built with Google WebRTC lib bug

---

Jenkinsfile.pdx
sdk/BUILD.gn

ERROR at
- sdk/BUILD.gn:623:10:
- sdk/BUILD.gn:709:11:
[UPC-5885]: https://ubiquiti.atlassian.net/browse/UPC-5885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix  ios_device_name Undefined identifier on macOS Platform

---

net/dcsctp/socket/stream_reset_handler.cc

Remove our customization to fix the data channel closing issue on WebUI.

fix: Datachannel closing issue on WebUI

---

Jenkinsfile.pdx
docker/Dockerfile.ubuntu.22.04.amd64

Looks like all that was needed is to regenerate docker image.
Added changes to make it easier to detect which dependency is failing to install

fix: Ubuntu 22.04 docker issue

---

modules/pacing/packet_router.cc

(cherry picked from commit 9d8fb97b3ca56ec9920271d8e545ae2ac76b143c)
No-try: true
Bug: chromium:1477075
Change-Id: Ia05a868bfab9e99ef66704e8d6bce516a7a43b0a Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/318440
Reviewed-by: Sergey Silkin <ssilkin@webrtc.org>
Commit-Queue: Harald Alvestrand <hta@webrtc.org>
Cr-Original-Commit-Position: refs/heads/main@{#40673} Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/319320
Reviewed-by: Philipp Hancke <phancke@microsoft.com>
Reviewed-by: Taylor Brandstetter <deadbeef@webrtc.org>
Cr-Commit-Position: refs/branch-heads/5845@{#7}
Cr-Branched-From: f80cf814353d11a9f22bef5ce5e8868f2c72f0d0-refs/heads/main@{#40319} (cherry picked from commit 402f60c2eabefbc7a120ec01659690c7fdf89769)

[Merge to 116] CHECK against overwrites in send_modules_map_

---

Jenkinsfile.pdx

**Stash preserves workspace files, but script never utilizing any of them.**
**Removing to improve compilation efficiency, takes over a minute on all platforms for processing stash and ustash.**

refactor: jenkins no use stash unstash workspace operation

---

sdk/BUILD.gn
sdk/objc/components/audio/RTCAudioProcessing.h
sdk/objc/native/src/unifi_capture_post_processing.mm

1. tvOS build script should not include the video capture framework.
2. Remove unnecessary method for iOS app.

fix: tvOS should not include the video capture framework

---

sdk/objc/components/audio/RTCAudioSession+Configuration.mm
sdk/objc/components/audio/RTCAudioSession.h
sdk/objc/components/audio/RTCAudioSession.mm
sdk/objc/components/audio/RTCNativeAudioSessionDelegateAdapter.mm
sdk/objc/native/src/audio/audio_device_ios.h
sdk/objc/native/src/audio/audio_device_ios.mm
sdk/objc/native/src/audio/audio_session_observer.h
sdk/objc/native/src/audio/voice_processing_audio_unit.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UP-1039)
**Description**
Issue is caused by the component sub type in webrtc lib is not aligned with app.
- App uses AudioRecorder and set the sub type to VPIO for mic audio data capture.
- WebRTC lib creates audio playout unit with sub type RemoteIO.
**Solution**
Make it aligned, when app switching the audio category, notify webrtc lib to re-create the audio playout unit with the right type.

fix: [UP-1039] iOS audio volume will be lowered when using data channel talkback with media live stream
