ubiquiti/ubnt_libjingle

video/video_stream_encoder.cc

https://ubiquiti.atlassian.net/browse/UPC-2843

[UPC-2843] Prevent frame dropping by encoder to avoid artifacts

---

sdk/objc/base/RTCVideoRenderer.h
sdk/objc/components/renderer/metal/RTCMTLNSVideoView.m
sdk/objc/components/renderer/metal/RTCMTLRenderer.h
sdk/objc/components/renderer/metal/RTCMTLRenderer.mm
sdk/objc/components/renderer/metal/RTCMTLVideoView.m
sdk/objc/components/renderer/opengl/RTCEAGLVideoView.m
sdk/objc/components/renderer/opengl/RTCNSGLVideoView.m

Ticket: https://ubiquiti.atlassian.net/browse/UPC-3478

iOS clear metal view to transparent

---

rtc_base/rate_limiter.cc
sdk/objc/components/audio/RTCAudioSession.h
sdk/objc/components/audio/RTCAudioSession.mm
sdk/objc/components/audio/RTCAudioSessionConfiguration.h
sdk/objc/components/audio/RTCAudioSessionConfiguration.m
sdk/objc/components/audio/RTCNativeAudioSessionDelegateAdapter.mm
sdk/objc/native/src/audio/audio_device_ios.h
sdk/objc/native/src/audio/audio_device_ios.mm
sdk/objc/native/src/audio/audio_session_observer.h
sdk/objc/native/src/audio/voice_processing_audio_unit.mm

Ticket: https://ubiquiti.atlassian.net/browse/UPC-3478

For iOS to control the microphone permission.

---

BUILD.gn
call/call.cc
call/call.h
call/degraded_call.h
call/rtp_demuxer.cc
call/rtp_demuxer.h
call/rtp_stream_receiver_controller.h
media/engine/fake_webrtc_call.h
webrtc.gni

https://ubiquiti.atlassian.net/browse/UPC-3700

feat: [UPC-3700] Talkback over WebRTC media stream

---

BUILD.gn
modules/congestion_controller/goog_cc/delay_based_bwe.cc
modules/congestion_controller/goog_cc/probe_controller.cc
modules/congestion_controller/goog_cc/probe_controller.h
modules/remote_bitrate_estimator/aimd_rate_control.cc
webrtc.gni

1. Remove state changes in AIMD state machine.
2. Add missed flag definition.

Remove state changes in AIMD state machine and add missed flag defination.

---

BUILD.gn
modules/pacing/bitrate_prober.h
modules/pacing/pacing_controller.cc
webrtc.gni

Remove customized video pausing changes.

Remove customized video pausing changes.

---

sdk/objc/native/src/audio/voice_processing_audio_unit.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-4460)

fix: [UPC-4460] Audio volume being played on iOS is lowered when WebRTC viewing is enabled

---

sdk/objc/components/audio/RTCAudioSession.h
sdk/objc/components/audio/RTCAudioSession.mm
sdk/objc/components/audio/RTCAudioSessionConfiguration.h
sdk/objc/components/audio/RTCNativeAudioSessionDelegateAdapter.mm
sdk/objc/native/src/audio/audio_device_ios.h
sdk/objc/native/src/audio/audio_device_ios.mm
sdk/objc/native/src/audio/audio_session_observer.h

1. Fix issue related to microphone enabled/disabled.
2. Add new flag for app to mute/unmute microphone.
More [details](https://ubiquiti.atlassian.net/wiki/spaces/UP/pages/2818572289/Google+WebRTC+mobile+app+media+stream+integration#iOS-Microphone---UI-Customization).

fix: iOS microphone related issues

---

media/sctp/dcsctp_transport.cc
modules/congestion_controller/goog_cc/probe_controller.cc
modules/congestion_controller/goog_cc/probe_controller.h
modules/remote_bitrate_estimator/aimd_rate_control.cc
rtc_base/rate_limiter.cc

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-4632)
Remove our customization about bandwidth probing and tuned parameters in addon.

feat: [UPC-4632] Remove the periodic probing.

---

DEPS

Update dependency ubnt_libjingle_component_src_build version to fix M113 build

deps: ubnt_libjingle_component_src_build version updated to v0.0.25

---

BUILD.gn

Added missing dependency of json code

fix: Add missing dependency of json code

---

api/video_codecs/video_encoder.cc
api/video_codecs/video_encoder.h
video/video_stream_encoder.cc

New api for debugging video suspend feature.

feat: Add api for suspended notification.

---

call/call.cc
call/call.h

Restore removed audio api customization

Fix custom audio interface broken by m109->m113 upgrade

---

Jenkinsfile.pdx
docker/Dockerfile.debian.11.amd64
docker/Dockerfile.debian.11.arm64
docker/Dockerfile.ubuntu.20.04.amd64
docker/Dockerfile.ubuntu.22.04.amd64

https://ubiquiti.atlassian.net/browse/UPC-5048

feat: [UPC-5048] Google WebRTC lib Jenkins build

---

sdk/BUILD.gn

[ticket](https://ubiquiti.atlassian.net/browse/UPC-5820)

fix: [UPC-5820] tvOS app cant be built with Google WebRTC lib

---

BUILD.gn
webrtc.gni

https://ubiquiti.atlassian.net/browse/UPC-5904

fix: [UPC-5904] Fix crash without default video decoder factory

---

sdk/objc/components/audio/RTCAudioSession.h
sdk/objc/components/audio/RTCAudioSession.mm
sdk/objc/components/audio/RTCAudioSessionConfiguration.h
sdk/objc/components/audio/RTCAudioSessionConfiguration.m
sdk/objc/components/audio/RTCNativeAudioSessionDelegateAdapter.mm
sdk/objc/native/src/audio/audio_device_ios.h
sdk/objc/native/src/audio/audio_device_ios.mm
sdk/objc/native/src/audio/audio_session_observer.h
sdk/objc/native/src/audio/voice_processing_audio_unit.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-6156)

fix: [UPC-6156] Google webRTC Media stream microphone is not working on iOS app for 2-way audio.

---

api/peer_connection_interface.h
call/call_config.cc
call/call_config.h
call/rtp_transport_config.h
call/rtp_transport_controller_send.cc
call/rtp_transport_controller_send.h
pc/peer_connection.cc
pc/peer_connection_factory.cc

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-6313)

feat: [UPC-6313] Let WebRTC addon support to monitor the status of pacer queue defined in Google WebRTC lib.

---

modules/audio_processing/audio_processing_impl.cc
modules/audio_processing/audio_processing_impl.h
modules/audio_processing/include/audio_processing.h
sdk/BUILD.gn
sdk/objc/api/peerconnection/RTCPeerConnectionFactory.h
sdk/objc/api/peerconnection/RTCPeerConnectionFactory.mm
sdk/objc/components/audio/RTCAudioProcessing.h
sdk/objc/native/api/objc_audio_processing.h
sdk/objc/native/api/objc_audio_processing.mm
sdk/objc/native/src/audio/audio_device_ios.h
sdk/objc/native/src/unifi_capture_post_processing.h
sdk/objc/native/src/unifi_capture_post_processing.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-6298)

feat: [UPC-6298] Audio level indicator when using media stream for mobile 2-way audio

---

api/peer_connection_interface.h
call/call_config.h
call/rtp_transport_config.h
call/rtp_transport_controller_send.cc
call/rtp_transport_controller_send.h
pc/peer_connection.cc

[Ticket](https://ubiquiti.atlassian.net/browse/UPC-6596)

fix: [UPC-6596] WebRTC peer connection leak issue

---

Jenkinsfile.pdx
docker/Dockerfile.ubuntu.22.04.amd64

Fix ubuntu 22.04 Jenkins build error.

fix: ubuntu 22.04 docker container error

---

sdk/objc/native/src/audio/audio_device_ios.mm

[Ticket](https://ubiquiti.atlassian.net/browse/UP-1806)
1. Add pointer checking to prevent crash at the moment
2. App should upload dSYM files to Firebase manually, e.g. make some scripts in Jenkins to upload the artifacts along with those dSYM files to Firebase.

fix: [UP-1806] iOS app crash which is related to webrtc lib

---

BUILD.gn
audio/audio_state.cc
media/engine/webrtc_voice_engine.cc
webrtc.gni

https://ubiquiti.atlassian.net/browse/UP-7188

fix: [UP-7188] Android app microphone in use before 2-way audio is activated
